version: "3.8"

services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty@2
      PGSTAT_TMP: /path/to/another/directory
      PGDATA: /var/lib/postgresql/data/db_data
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,chmod=777
    command: ["postgres", "-c", "max_connections=300"]
    networks:
      - db_network

  app:
    build: ./app
    image: olympic_loader:latest
    container_name: app
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./app:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: olympic
      DB_USER: postgres
      DB_PASSWORD: Qwerty@2
    command: ["python", "app.py", "input/Athletes_summer_games.csv", "input/Athletes_winter_games.csv"]
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  db_data:
    driver: local