version: "3.8"

services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Qwerty@2
      POSTGRES_DB: olympic
      PGSTAT_TMP: /path/to/another/directory
    volumes:
      - ./data_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "max_connections=300"]

  app:
    build: ./app
    image: olympic_loader:latest
    container_name: app
    depends_on:
      - db
    volumes:
      - ./app:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: olympic
      DB_USER: dev
      DB_PASSWORD: Qwerty@2
    command: ["python", "app.py","archive/Athletes_summer_games.csv","archive/Athletes_winter_games.csv"]

volumes:
  db_data:
    driver: local